
-- 1.2.3.4.5.6.7.

SELECT COALESCE(NULL, 5); -- 5
SELECT COALESCE(10, 5); -- 10

SELECT COALESCE((4)::BOOLEAN::INTEGER, 0);
SELECT COALESCE((NULL)::BOOLEAN::INTEGER, 0);


SELECT (NULL)::BOOLEAN; -- NULL
SELECT (NULL)::BOOLEAN::INTEGER; -- NULL

